// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPgprIv_WKgT5ST0nqRNv1XOwTfMKaOA',
    appId: '1:582728644523:web:15c52e84b63228de2b84ee',
    messagingSenderId: '582728644523',
    projectId: 'shopvault-69e12',
    authDomain: 'shopvault-69e12.firebaseapp.com',
    storageBucket: 'shopvault-69e12.firebasestorage.app',
    measurementId: 'G-9CLX40DKDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Iio6z-RgnjmiLu4CB-qJ1ltzclW_V2E',
    appId: '1:582728644523:android:1465b6fb04c855a32b84ee',
    messagingSenderId: '582728644523',
    projectId: 'shopvault-69e12',
    storageBucket: 'shopvault-69e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHnTKftqRPzgxxum6nQQy92pU0l60hei8',
    appId: '1:582728644523:ios:d3a7006644ccd3172b84ee',
    messagingSenderId: '582728644523',
    projectId: 'shopvault-69e12',
    storageBucket: 'shopvault-69e12.firebasestorage.app',
    iosClientId: '582728644523-fl086fer9ccugh8epna3s4qdh3msdank.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopvalut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHnTKftqRPzgxxum6nQQy92pU0l60hei8',
    appId: '1:582728644523:ios:d3a7006644ccd3172b84ee',
    messagingSenderId: '582728644523',
    projectId: 'shopvault-69e12',
    storageBucket: 'shopvault-69e12.firebasestorage.app',
    iosClientId: '582728644523-fl086fer9ccugh8epna3s4qdh3msdank.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopvalut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPgprIv_WKgT5ST0nqRNv1XOwTfMKaOA',
    appId: '1:582728644523:web:bbc64b49b6a6e9bf2b84ee',
    messagingSenderId: '582728644523',
    projectId: 'shopvault-69e12',
    authDomain: 'shopvault-69e12.firebaseapp.com',
    storageBucket: 'shopvault-69e12.firebasestorage.app',
    measurementId: 'G-M51QGVT296',
  );
}
